packaging_format = 2

id = "osticket"
name = "osTicket"
description.en = "Open source support ticket system"
description.fr = "Système de ticket de support open source"

version = "1.17.3~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://osticket.com"
demo = "http://www.ostickethacks.com/demo/demo_info.php"
userdoc = "https://docs.osticket.com"
code = "https://github.com/osTicket/osTicket"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/osticket"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["en_US", "fr", "ar_EG", "ar_SA", "az", "bg", "bn", "bs", "ca", "cs", "da", "de", "el", "en_GB", "es_AR", "es_ES", "es_MX", "et", "eu", "fa", "fi", "he", "hi", "hr", "hu", "id", "is", "it", "ja", "ka", "km", "ko", "lt", "lv", "mk", "mn", "ms", "nl", "no", "pl", "pt_BR", "pt_PT", "ro", "ru", "sk", "sl", "sq", "sr", "sr_CS", "sv_SE", "sw", "th", "tr", "uk", "ur_IN", "ur_PK", "vi", "zh_CN", "zh_TW"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.plugin-autocloser]
        url = "https://github.com/clonemeagain/plugin-autocloser/archive/b9db66273728296723a3bb9048bfce8e3d7b2d24.tar.gz"
        sha256 = "ae255123278b2a04046c3efd49a042f9fa18cd08ee43e28ced34aa44cf4f9c7c"
        autoupdate.upstream = "https://github.com/clonemeagain/plugin-autocloser"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-preventautoscroll]
        url = "https://github.com/clonemeagain/osticket-plugin-preventautoscroll/archive/2b5c51200d0f64da15d1f504e9294d877577fc46.tar.gz"
        sha256 = "0e31ea961668097e739de0da4aaf41b36ebf71a56508642500ec3f5ec59ede19"
        autoupdate.upstream = "https://github.com/clonemeagain/osticket-plugin-preventautoscroll"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-microsoft-teams]
        url = "https://github.com/ipavlovi/osTicket-Microsoft-Teams-plugin/archive/bebf7010e8817cf5495e9d3ab6f30e0e8e270d41.tar.gz"
        sha256 = "7e9825d26b7758255d73c79f763909f22b1b1d909cb226d901f1231ec98b3fd2"
        autoupdate.upstream = "https://github.com/ipavlovi/osTicket-Microsoft-Teams-plugin"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.core-plugins]
        url = "https://github.com/osTicket/osTicket-plugins/archive/685d03a06a6167f348547a444973ce97b68b73ba.tar.gz"
        sha256 = "5eaa2aaa9595c5f269ea7c288f27f8fae65af8c4cdef4bebfa1d7de2090aed18"
        autoupdate.upstream = "https://github.com/osTicket/osTicket-plugins"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-mentioner]
        url = "https://github.com/clonemeagain/osticket-plugin-mentioner/archive/48db3aca9f0c79b90315a0b0575e21617aa2c57c.tar.gz"
        sha256 = "c88a925be63c2b5cf2677f23e442a3c31a6657835f8c3423828e01b7656cac33"
        autoupdate.upstream = "https://github.com/clonemeagain/osticket-plugin-mentioner"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-fwd-rewriter]
        url = "https://github.com/clonemeagain/plugin-fwd-rewriter/archive/2c5e3bad0f0cb94a1b51a33a854cfd551ea67e30.tar.gz"
        sha256 = "c12f1757110ef5141f274b5dc10be186c1d608d2bed74d48f41bce956abc98a3"
        autoupdate.upstream = "https://github.com/clonemeagain/plugin-fwd-rewriter"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.main]
        url = "https://github.com/osTicket/osTicket/releases/download/v1.17.3/osTicket-v1.17.3.zip"
        sha256 = "be3ade536a19b875e16fe0d9716e07f3897f5c0cdbd4efe4ff17ab262d98bed3"
        autoupdate.strategy = "latest_github_tag"
 
        [resources.sources.plugin-attachment_preview]
        url = "https://github.com/clonemeagain/attachment_preview/archive/de4d6a83fc7947d39b3493ad1ad1ef864a3a80ce.tar.gz"
        sha256 = "1ad19e824a6ea71ff17e7d0b3665d77d1b223a8a77d1d810b10f76b6879d1864"
        autoupdate.upstream = "https://github.com/clonemeagain/attachment_preview"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-fetch-note]
        url = "https://github.com/bkonetzny/osticket-fetch-note/archive/7bd28052a33d448db68e0393ca5d92f1b1744283.tar.gz"
        sha256 = "d95c8c744cdad20b25fe4053ca795d118e82c36a5f0b86973da47209b5ac9cc0"
        autoupdate.upstream = "https://github.com/bkonetzny/osticket-fetch-note"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-slack]
        url = "https://github.com/clonemeagain/osticket-slack/archive/15c0cadfbc0c0548cde5750eda5f29d36381683b.tar.gz"
        sha256 = "635e024176742116f288146b6d7397f614be0ef812cbbffbc649789cc51bbb79"
        autoupdate.upstream = "https://github.com/clonemeagain/osticket-slack"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-field-radiobuttons]
        url = "https://github.com/Micke1101/OSTicket-plugin-field-radiobuttons/archive/5e5173b5b15f25a8f681f6df767ecd7f6d413530.tar.gz"
        sha256 = "cfd135076710cf4eaeb4966af73009bc20618ed8cc9d618f1ddf6499b381c348"
        autoupdate.upstream = "https://github.com/Micke1101/OSTicket-plugin-field-radiobuttons"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-mattermost]
        url = "https://github.com/pberndro/osticket-mattermost/archive/8ac5224c121e765f22237818da1b8c189a9bd647.tar.gz"
        sha256 = "d18e2c796bd96c1016334195e816445d684a10e933f997a789d340eee75c7db7"
        autoupdate.upstream = "https://github.com/pberndro/osticket-mattermost"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.plugin-archiver]
        url = "https://github.com/clonemeagain/osticket-plugin-archiver/archive/a1e20bb230f0943769c0e548539d553881ecfb1e.tar.gz"
        sha256 = "f2b549e208ccecdb7334dae568eef90fdaecad381f274d6af7a7564b5f9b03fe"
        autoupdate.upstream = "https://github.com/clonemeagain/osticket-plugin-archiver"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.0-mysql php8.0-gd php-php-gettext php8.0-imap php8.0-fpm php8.0-mbstring php8.0-xml php8.0-zip php8.0-intl php8.0-curl curl"
    
    [resources.database]
    type = "mysql"
